inputs = {
    "membranova-stena": {
        "od": 57,
        "t_nom": 5,
        "p_op": 10,
        "temp_op": 315,
        "material": "12022",
    },
    "strop-ohniska": {
        "od": 57,
        "t_nom": 5,
        "p_op": 10,
        "temp_op": 315,
        "material": "12022",
    },
    "strop-medzitahu": {
        "od": 57,
        "t_nom": 5,
        "p_op": 10,
        "temp_op": 305,
        "material": "12022",
    },
    "zadna-stena-2-tah": {
        "od": 57,
        "t_nom": 5,
        "p_op": 10,
        "temp_op": 260,
        "material": "12022",
    },
    "p-l-stena-2-tah": {
        "od": 57,
        "t_nom": 5,
        "p_op": 10,
        "temp_op": 260,
        "material": "12022",
    },
    "vystupny-prehrievac": {
        "od": 57,
        "t_nom": 5,
        "p_op": 10,
        "temp_op": 525,
        "material": "15128",
    },
    "salavy-prehrievac": {
        "od": 57,
        "t_nom": 5,
        "p_op": 10,
        "temp_op": 480,
        "material": "15128",
    },
    "mreza": {
        "od": 57,
        "t_nom": 5,
        "p_op": 10,
        "temp_op": 325,
        "material": "12022",
    },
}
